/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Resource Planning
 * For managing the enterprise\'s universal resources
 *
 * The version of the OpenAPI document: 1.0
 * Contact: shmonov.mv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

